{
  device: [
            {name: "未分配",id: "1"},
            {name: "办公使用",id: "2"},
            {name: "闲置",id: "3"},
            {name: "维修",id: "4"},
            {name: "借用",id: "5"},
            {name: "报废",id: "6"},
            {name: "报废借用",id: "7"},
            {name: "报废清理",id: "8"},
            {name: "状态不详",id: "9"}
          ],
  part:   [
            {name: "未分配",id: "1"},
            {name: "已分配",id: "2"},
            {name: "闲置",id: "3"}
          ]
}
