{
  device: [
            {name: "闲置",id: "1"},
            {name: "办公使用",id: "2"},
            {name: "人员借用",id: "3"},
            {name: "设备借用",id: "4"},
          ],
  part:   [
            {name: "未分配",id: "1"},
            {name: "已分配",id: "2"},
            {name: "闲置",id: "3"}
          ]
}
